CXX := clang++
GTEST_DIR := thrid_party/gtest

libgtest_main.a: gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

gtest-all.o:
	$(CXX) \
		-W -Wall -Wextra -stdlib=libc++ \
		-DGTEST_HAS_TR1_TUPLE=0 \
		-I$(GTEST_DIR) \
		-I$(GTEST_DIR)/include \
		-g \
		-c \
		$(GTEST_DIR)/src/gtest-all.cc

gtest_main.o:
	$(CXX) \
		-W -Wall -Wextra -stdlib=libc++ \
		-DGTEST_HAS_TR1_TUPLE=0 \
		-I$(GTEST_DIR) \
		-I$(GTEST_DIR)/include \
		-g \
		-c \
		$(GTEST_DIR)/src/gtest_main.cc
