#ifndef EBITEN_VERSION_HPP
#define EBITEN_VERSION_HPP

#define EBITEN_VERSION          (00000)
#define EBITEN_VERSION_MAJOR    (EBITEN_VERSION / 10000)
#define EBITEN_VERSION_MINOR    ((EBITEN_VERSION / 100) % 100)
#define EBITEN_VERSION_SUBMINOR (EBITEN_VERSION % 100)

#endif
